# Generated by Django 6.0.3 on 2026-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=50)),
                ('form_step', models.IntegerField()),
                ('interested', models.BooleanField(null=True)),
                ('reschedule', models.BooleanField(null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('proposed_time_ok', models.BooleanField(null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=20, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('final_confirmation', models.CharField(blank=True, max_length=20, null=True)),
                ('communication_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
