# Generated by Django 6.0.3 on 2026-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresponse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='formresponse',
            name='form_step',
        ),
        migrations.RemoveField(
            model_name='formresponse',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='formresponse',
            name='current_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='lead_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
