# Generated by Django 6.0.3 on 2026-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_formresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='interested',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='lead_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='proposed_time_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='reschedule',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
