# Generated by Django 6.0.3 on 2026-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_formresponse_interested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='taskid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
